update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 10776 Kingstone Maple';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 1573 Frosty White';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 1595 Black';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4552 Ebony Star';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4781 Sunstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4789 Limestone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4790 Greystone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4791 Willowstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4794 Windswept Bronze';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4795 Windswept Pewter';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4882 Oiled Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4883 Sable Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4884 Flame Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4885 Green Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4886 Pearl Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 4887 Tan Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 7921 Tuscan Walnut';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 7942 Cocobala';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate 7948 Mambo';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate D403 White Sand';
update items set base_price = 178.83 where name = 'CTOP Corner - Classic (3 Week Lead Time) | Laminate D92 Dove Grey';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 10776 Kingstone Maple';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 1573 Frosty White';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 1595 Black';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4781 Sunstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4789 Limestone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4790 Greystone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4791 Willowstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4794 Windswept Bronze';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4795 Windswept Pewter';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4882 Oiled Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4883 Sable Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4884 Flame Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4885 Green Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4886 Pearl Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 4887 Tan Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 7921 Tuscan Walnut';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 7942 Cocobala';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate 7948 Mambo';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate D403 White Sand';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura (3 Week Lead Time) | Laminate D92 Dove Grey';
update items set base_price = 178.83 where name = 'CTOP Corner - Futura | Laminate 4552 Ebony Star';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 10776 Kingstone Maple';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 1573 Frosty White';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 1595 Black';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4552 Ebony Star';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4781 Sunstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4789 Limestone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4790 Greystone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4791 Willowstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4794 Windswept Bronze';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4795 Windswept Pewter';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4882 Oiled Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4883 Sable Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4884 Flame Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4885 Green Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4886 Pearl Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 4887 Tan Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 7921 Tuscan Walnut';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 7942 Cocobala';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate 7948 Mambo';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate D403 White Sand';
update items set base_price = 178.83 where name = 'CTOP Corner - Geneva (3 Week Lead Time) | Laminate D92 Dove Grey';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 10776 Kingstone Maple';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 1573 Frosty White';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 1595 Black';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4552 Ebony Star';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4781 Sunstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4789 Limestone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4790 Greystone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4791 Willowstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4794 Windswept Bronze';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4795 Windswept Pewter';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4882 Oiled Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4883 Sable Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4884 Flame Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4885 Green Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4886 Pearl Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 4887 Tan Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 7921 Tuscan Walnut';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 7942 Cocobala';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate 7948 Mambo';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate D403 White Sand';
update items set base_price = 178.83 where name = 'CTOP Corner - Nova (3 Week Lead Time) | Laminate D92 Dove Grey';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 10776 Kingstone Maple';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 1573 Frosty White';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 1595 Black';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4552 Ebony Star';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4781 Sunstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4789 Limestone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4790 Greystone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4791 Willowstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4882 Oiled Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 4884 Flame Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 7921 Tuscan Walnut';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 7942 Cocobala';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate 7948 Mambo';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate D403 White Sand';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo (3 Week Lead Time) | Laminate D92 Dove Grey';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4794 Windswept Bronze';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4795 Windswept Pewter';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4883 Sable Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4885 Green Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4886 Pearl Soapstone';
update items set base_price = 178.83 where name = 'CTOP Corner - Tempo | Laminate 4887 Tan Soapstone';
